change to use simplecov
... instead of deprecated codeclimate-test-reporter

This fixes an error while running coverage task,
which occurs with: ruby 3.1.2p20 (2022-04-12 revision 4491bb740a) [x86_64-darwin21]

Error summary:

> Coverage report generated for RSpec to /Users/gemmaro/repos/jkf/coverage. 2269 / 2438 LOC (93.07%) covered.
> Formatter CodeClimate::TestReporter::Formatter failed with NoMethodError: undefined method `map' for #<SimpleCov::Result: ...
> ...
>
>         simplecov_results = results.map do |command_name, data|
>                                    ^^^^
> Did you mean?  tap (/Users/gemmaro/.rbenv/versions/3.1.2/lib/ruby/gems/3.1.0/gems/codeclimate-test-reporter-1.0.9/lib/code_climate/test_reporter/formatter.rb:16:in `format')